services:
  eyri_app:
    build:
      context: .
      dockerfile: Containerfile
    restart: unless-stopped
    env_file:
      - .env
    init: true
    volumes:
      - eyri-data:/app/data

volumes:
  eyri-data:
